---
version: 1.0

globel:

admin:
  params:
    orgName: Org1
    orgMSP: Org1MSP
    orgHost: org1.example.com
    orgAdmin: Admin
    configPath: ../network/orgs/admin/admin-org1.yaml
  envs:
    - key: DISCOVERY_AS_LOCALHOST
      val: true
    - key: TEST_IN_SHELL
      val: false

app:
  params:
    orgName: Org1
    orgMSP: Org1MSP
    orgHost: org1.example.com
    orgAdmin: Admin
    configPath: ../network/orgs/app/app-org1.yaml

    orgUser: User1
    credPath: ../network/orgs/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp
    certPath: ../network/orgs/peerOrganizations/org1.example.com/users/User1@org1.example.com/msp/signcerts/User1@org1.example.com-cert.pem
  envs:
    - key: DISCOVERY_AS_LOCALHOST
      val: true
    - key: TEST_IN_SHELL
      val: false
